FROM python:3.11.6-slim-bookworm as base

# Install poetry
RUN pip install pipx
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"
ENV PATH=".venv/bin/:$PATH"

# https://python-poetry.org/docs/configuration/#virtualenvsin-project
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/app
COPY pyproject.toml poetry.lock ./

RUN poetry install --extras "ui vector-stores-qdrant llms-gemini embeddings-gemini"

FROM base as app

ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080

WORKDIR /home/app

RUN mkdir local_data
RUN mkdir models
COPY --from=dependencies /home/worker/app/.venv/ .venv
COPY private_gpt/ private_gpt
COPY fern/ fern
COPY *.yaml *.md ./
COPY scripts/ scripts

ENV PYTHONPATH="$PYTHONPATH:/private_gpt/"

ENTRYPOINT python -m private_gpt
